/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable import/no-mutable-exports */
import i18next from 'i18next';
import ar from './navigation-i18n/ar';
import en from './navigation-i18n/en';
import tr from './navigation-i18n/tr';

i18next.addResourceBundle('en', 'navigation', en);
i18next.addResourceBundle('tr', 'navigation', tr);
i18next.addResourceBundle('ar', 'navigation', ar);
const getUser = JSON.parse(localStorage.getItem('user_profile'));
let userRoles;
if (getUser) {
  userRoles = getUser[0]?.roles;
}
let navigationConfig = [];
if (!userRoles) {
  navigationConfig = [];
}

if (userRoles) {
  if (userRoles === 'SUPER_ADMIN' || userRoles === 'ADMIN' || userRoles === 'SUPERVISOR') {
    navigationConfig = [
      {
        id: 'applications',
        title: 'APPLICATIONS',
        translate: 'APPLICATIONS',
        type: 'group',
        icon: 'apps',
        children: [
          {
            id: 'dasboard',
            title: 'DASHBOARD',
            // translate: 'Dasboard',
            type: 'item',
            icon: 'home',
            url: 'apps/dashboard/dashboardPages',
          },
          {
            id: 'registration',
            title: 'REGISTRATION',
            type: 'collapse',
            icon: 'library_add',
            children: [
              {
                id: 'purchaseOrder',
                title: 'Purchase Order',
                type: 'item',
                icon: 'list_alt',
                url: 'apps/registration/purchaseOrder',
              },
              {
                id: 'model',
                title: 'Types',
                type: 'item',
                icon: 'atm',
                url: 'apps/registration/model',
              },
              {
                id: 'machine',
                title: 'Models',
                type: 'item',
                icon: 'pages',
                url: 'apps/registration/machine',
              },
              {
                id: 'management',
                title: 'User Managements',
                type: 'item',
                icon: 'account_balance',
                url: 'apps/registration/management',
              },
              // {
              //   id: 'stagingpic',
              //   title: 'PIC Staging',
              //   type: 'item',
              //   icon: 'assignment_ind',
              //   url: 'apps/registration/stagingPic',
              // },
              // {
              //   id: 'picMover',
              //   title: 'PIC Mover',
              //   type: 'item',
              //   icon: 'group',
              //   url: 'apps/registration/picMover',
              // },
              // {
              //   id: 'picTSS',
              //   title: 'PIC TSS',
              //   type: 'item',
              //   icon: 'archive',
              //   url: 'apps/registration/picTSS',
              // },
              // {
              //   id: 'machineSpesification',
              //   title: 'List Specification',
              //   type: 'item',
              //   icon: 'keyboard',
              //   url: '/apps/registration/machineSpesification',
              // },
              {
                id: 'partNumber',
                title: 'Detail PartNumber',
                type: 'item',
                icon: 'keyboard',
                url: 'apps/registration/partNumber',
              },
              {
                id: 'detailSpesification',
                title: 'Detail Specification',
                type: 'item',
                icon: 'keyboard',
                url: '/apps/registration/detailSpesification',
              },
              {
                id: 'detailPrestaging',
                title: 'Detail Prestaging',
                type: 'item',
                icon: 'keyboard',
                url: 'apps/registration/prestaging',
              },
              {
                id: 'detailPreloading',
                title: 'Detail Preloading',
                type: 'item',
                icon: 'keyboard',
                url: 'apps/registration/preloading',
              },
              {
                id: 'settingCkecklistStaging',
                title: 'Setting Pre Staging',
                type: 'item',
                icon: 'settings',
                url: 'apps/registration/settingPreStaging',
              },
              {
                id: 'warehouse',
                title: 'Warehouse',
                type: 'item',
                icon: 'account_balance',
                url: 'apps/registration/warehouse',
              },
              {
                id: 'batch',
                title: 'Batch',
                type: 'item',
                icon: 'batch_prediction',
                url: 'apps/registration/batch',
              },
              {
                id: 'customer',
                title: 'Customer',
                type: 'item',
                icon: 'account_circle',
                url: 'apps/registration/customer',
              },
              {
                id: 'statusPo',
                title: 'Status PO',
                type: 'item',
                icon: 'list_alt',
                url: 'apps/registration/statusPo',
              },
              {
                id: 'style',
                title: 'Style',
                type: 'item',
                icon: 'border_style',
                url: 'apps/registration/style',
              },
            ],
          },
          {
            id: 'spesification',
            title: 'SPECIFICATION',
            type: 'item',
            icon: 'forward_rounded',
            url: 'apps/spesification',
          },
          {
            id: 'staggingRegistry',
            title: 'STAGING REGISTRATION',
            type: 'item',
            icon: 'post_add',
            url: 'apps/porcaheOrder',
          },
          {
            id: 'preStaging',
            title: 'PRE STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'checklistStaging',
                title: 'Pre Staging Checklist',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/checklistStagging/',
              },
            ],
          },
          {
            id: 'staging',
            title: 'STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'stagingOldmachine',
                title: 'Staging Old Machine',
                type: 'item',
                disabled: true,
                icon: 'clear_all',
                url: 'apps/viewOldMachine',
                // url: 'apps/stagging/oldMachine',
              },
              {
                id: 'staggingNewMachine',
                title: 'Staging New Machine',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/viewNewMachine/',
                // url: 'apps/stagging/newMachine/',
              },
              {
                id: 'inspeksiTesting',
                title: 'Pre Loading Inspection',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/inspeksiTestings/',
              },
            ],
          },
          {
            id: 'statusDelivery',
            title: 'STATUS DELIVERY',
            type: 'item',
            icon: 'local_shipping',
            url: 'apps/statusDelivery',
          },
          {
            id: 'warehose',
            title: 'WAREHOUSE',
            type: 'collapse',
            icon: 'forward_rounded',
            children: [
              {
                id: 'warehouseTransfer',
                title: 'WAREHOUSE TRANSFER',
                type: 'item',
                icon: 'forward_rounded',
                url: 'apps/warehouseTransfer',
              },
              {
                id: 'deliveryRequest',
                title: 'Delivery Request',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/deliveryRequest',
              },
            ],
          },
          {
            id: 'summaryReport',
            title: 'SUMMARY',
            type: 'collapse',
            icon: 'library_books',
            children: [
              {
                id: 'summaryMachine',
                title: 'Summary Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/machine',
              },
              {
                id: 'summaryAccessories',
                title: 'Summary Accessories',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/accessories',
              },
              {
                id: 'summaryNewMachine',
                title: 'Summary New Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/Summary/newMachine',
              },
              {
                id: 'summaryOldMachine',
                title: 'Summary Old Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/oldMachine',
              },
              {
                id: 'summaryDeliveryStatus',
                title: 'Summary Warehouse Transper',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouseTransper',
              },
              {
                id: 'summarywarehouse',
                title: 'Summary Warehouse',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouse',
              },
              {
                id: 'summarypreStaging',
                title: 'Summary Pre Staging',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/preStaging',
              },
              {
                id: 'durationStagingSummary',
                title: 'Duration Staging Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationStagingSummary',
              },
              {
                id: 'DurationReportSummary',
                title: 'Duration Report Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationReportSummary',
              },
              {
                id: 'developmentSummary',
                title: 'Development Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/developmentSummary',
              },
              {
                id: 'warehouse',
                title: 'Summary Status Delivery',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/statusDelivery',
              },
              {
                id: 'summaryUps',
                title: 'Summary UPS',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/ups',
              },
              {
                id: 'implementationTable',
                title: 'Implementation Table',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/implementationTable',
              },
            ],
          },
          {
            id: 'mydatindo',
            title: 'MY DATINDO INTEGRATION',
            type: 'item',
            icon: 'launch',
            url: 'apps/myDatindoIntergration',
          },
        ],
      },
    ];
  } else if (userRoles === 'GUEST' || userRoles === 'GUEST_DIP') {
    // console.log('OPERATOR_MOVER');
    navigationConfig = [
      {
        id: 'applications',
        title: 'APPLICATIONS',
        translate: 'APPLICATIONS',
        type: 'group',
        icon: 'apps',
        children: [
          {
            id: 'dasboard',
            title: 'DASHBOARD',
            // translate: 'Dasboard',
            type: 'item',
            icon: 'home',
            url: 'apps/dashboard/dashboardPages',
          },
          {
            id: 'spesification',
            title: 'SPECIFICATION',
            type: 'item',
            icon: 'forward_rounded',
            url: 'apps/spesification',
          },
          {
            id: 'staggingRegistry',
            title: 'STAGING REGISTRATION',
            type: 'item',
            icon: 'post_add',
            url: 'apps/porcaheOrder',
          },
          {
            id: 'preStaging',
            title: 'PRE STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'checklistStaging',
                title: 'Pre Staging Checklist',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/checklistStagging/',
              },
            ],
          },
          {
            id: 'staging',
            title: 'STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'stagingOldmachine',
                title: 'Staging Old Machine',
                type: 'item',
                disabled: true,
                icon: 'clear_all',
                url: 'apps/viewOldMachine',
                // url: 'apps/stagging/oldMachine',
              },
              {
                id: 'staggingNewMachine',
                title: 'Staging New Machine',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/viewNewMachine/',
                // url: 'apps/stagging/newMachine/',
              },
              {
                id: 'inspeksiTesting',
                title: 'Pre Loading Inspection',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/inspeksiTestings/',
              },
            ],
          },
          {
            id: 'statusDelivery',
            title: 'STATUS DELIVERY',
            type: 'item',
            icon: 'local_shipping',
            url: 'apps/statusDelivery',
          },
          {
            id: 'warehose',
            title: 'WAREHOUSE',
            type: 'collapse',
            icon: 'forward_rounded',
            children: [
              {
                id: 'warehouseTransfer',
                title: 'WAREHOUSE TRANSFER',
                type: 'item',
                icon: 'forward_rounded',
                url: 'apps/warehouseTransfer',
              },
              {
                id: 'deliveryRequest',
                title: 'Delivery Request',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/deliveryRequest',
              },
            ],
          },
          {
            id: 'summaryReport',
            title: 'SUMMARY',
            type: 'collapse',
            icon: 'library_books',
            children: [
              {
                id: 'summaryMachine',
                title: 'Summary Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/machine',
              },
              {
                id: 'summaryAccessories',
                title: 'Summary Accessories',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/accessories',
              },
              {
                id: 'summaryNewMachine',
                title: 'Summary New Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/Summary/newMachine',
              },
              {
                id: 'summaryOldMachine',
                title: 'Summary Old Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/oldMachine',
              },
              {
                id: 'summaryDeliveryStatus',
                title: 'Summary Warehouse Transper',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouseTransper',
              },
              {
                id: 'summarywarehouse',
                title: 'Summary Warehouse',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouse',
              },
              {
                id: 'summarypreStaging',
                title: 'Summary Pre Staging',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/preStaging',
              },
              {
                id: 'durationStagingSummary',
                title: 'Duration Staging Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationStagingSummary',
              },
              {
                id: 'durationReportSummary',
                title: 'Duration Report Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationReportSummary',
              },

              {
                id: 'developmentSummary',
                title: 'Development Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/developmentSummary',
              },
              {
                id: 'warehouse',
                title: 'Summary Status Delivery',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/statusDelivery',
              },
              {
                id: 'summaryUps',
                title: 'Summary UPS',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/ups',
              },
              {
                id: 'implementationTable',
                title: 'Implementation Table',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/implementationTable',
              },
            ],
          },
          {
            id: 'mydatindo',
            title: 'MY DATINDO INTEGRATION',
            type: 'item',
            icon: 'launch',
            url: 'apps/myDatindoIntergration',
          },
        ],
      },
    ];
  } else if (userRoles === 'OPERATOR_MOVER') {
    // console.log('OPERATOR_MOVER');
    navigationConfig = [
      {
        id: 'applications',
        title: 'APPLICATIONS',
        translate: 'APPLICATIONS',
        type: 'group',
        icon: 'apps',
        children: [
          {
            id: 'staging',
            title: 'STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'inspeksiTesting',
                title: 'Pre Loading Inspection',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/inspeksiTestings/',
              },
            ],
          },
          {
            id: 'statusDelivery',
            title: 'STATUS DELIVERY',
            type: 'item',
            icon: 'local_shipping',
            url: 'apps/statusDelivery',
          },
        ],
      },
    ];
  } else if (userRoles === 'GUEST_BANK') {
    navigationConfig = [
      {
        id: 'applications',
        title: 'APPLICATIONS',
        translate: 'APPLICATIONS',
        type: 'group',
        icon: 'apps',
        children: [
          // {
          //   id: 'staggingRegistry',
          //   title: 'STAGING REGISTRATION',
          //   type: 'item',
          //   icon: 'post_add',
          //   url: 'apps/porcaheOrder',
          // },
          {
            id: 'spesification',
            title: 'SPECIFICATION',
            type: 'item',
            icon: 'forward_rounded',
            url: 'apps/spesification',
          },
          {
            id: 'statusDelivery',
            title: 'STATUS DELIVERY',
            type: 'item',
            icon: 'local_shipping',
            url: 'apps/statusDelivery',
          },
        ],
      },
    ];
  } else if (userRoles === 'OPERATOR_DIP' || userRoles === 'OPERATOR_TSS') {
    // console.log('OPERATOR_DIP, SUPERVISOR');
    navigationConfig = [
      {
        id: 'applications',
        title: 'APPLICATIONS',
        translate: 'APPLICATIONS',
        type: 'group',
        icon: 'apps',
        children: [
          {
            id: 'dasboard',
            title: 'DASHBOARD',
            // translate: 'Dasboard',
            type: 'item',
            icon: 'home',
            url: 'apps/dashboard/dashboardPages',
          },
          {
            id: 'spesification',
            title: 'SPECIFICATION',
            type: 'item',
            icon: 'forward_rounded',
            url: 'apps/spesification',
          },
          {
            id: 'staggingRegistry',
            title: 'STAGING REGISTRATION',
            type: 'item',
            icon: 'post_add',
            url: 'apps/porcaheOrder',
          },
          {
            id: 'preStaging',
            title: 'PRE STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'checklistStaging',
                title: 'Pre Staging Checklist',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/checklistStagging/',
              },
            ],
          },
          {
            id: 'staging',
            title: 'STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'stagingOldmachine',
                title: 'Staging Old Machine',
                type: 'item',
                disabled: true,
                icon: 'clear_all',
                url: 'apps/viewOldMachine',
                // url: 'apps/stagging/oldMachine',
              },
              {
                id: 'staggingNewMachine',
                title: 'Staging New Machine',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/viewNewMachine/',
                // url: 'apps/stagging/newMachine/',
              },
              {
                id: 'inspeksiTesting',
                title: 'Pre Loading Inspection',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/inspeksiTestings/',
              },
            ],
          },
          {
            id: 'statusDelivery',
            title: 'STATUS DELIVERY',
            type: 'item',
            icon: 'local_shipping',
            url: 'apps/statusDelivery',
          },
          {
            id: 'warehose',
            title: 'WAREHOUSE',
            type: 'collapse',
            icon: 'forward_rounded',
            children: [
              {
                id: 'warehouseTransfer',
                title: 'WAREHOUSE TRANSFER',
                type: 'item',
                icon: 'forward_rounded',
                url: 'apps/warehouseTransfer',
              },
              {
                id: 'deliveryRequest',
                title: 'Delivery Request',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/deliveryRequest',
              },
            ],
          },
          {
            id: 'summaryReport',
            title: 'SUMMARY',
            type: 'collapse',
            icon: 'library_books',
            children: [
              {
                id: 'summaryMachine',
                title: 'Summary Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/machine',
              },
              {
                id: 'summaryAccessories',
                title: 'Summary Accessories',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/accessories',
              },
              {
                id: 'summaryNewMachine',
                title: 'Summary New Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/Summary/newMachine',
              },
              {
                id: 'summaryOldMachine',
                title: 'Summary Old Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/oldMachine',
              },
              {
                id: 'summaryDeliveryStatus',
                title: 'Summary Warehouse Transper',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouseTransper',
              },
              {
                id: 'summarywarehouse',
                title: 'Summary Warehouse',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouse',
              },
              {
                id: 'summarypreStaging',
                title: 'Summary Pre Staging',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/preStaging',
              },
              {
                id: 'durationStagingSummary',
                title: 'Duration Staging Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationStagingSummary',
              },
              {
                id: 'durationReportSummary',
                title: 'Duration Report Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationReportSummary',
              },
              {
                id: 'developmentSummary',
                title: 'Development Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/developmentSummary',
              },
              {
                id: 'warehouse',
                title: 'Summary Status Delivery',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/statusDelivery',
              },
              {
                id: 'summaryUps',
                title: 'Summary UPS',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/ups',
              },
              {
                id: 'deliveryRequest',
                title: 'Delivery Request',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/deliveryRequest',
              },
              {
                id: 'implementationTable',
                title: 'Implementation Table',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/implementationTable',
              },
            ],
          },
          {
            id: 'mydatindo',
            title: 'MY DATINDO INTEGRATION',
            type: 'item',
            icon: 'launch',
            url: 'apps/myDatindoIntergration',
          },
        ],
      },
    ];
  } else if (userRoles === 'GUEST_RELATED') {
    // console.log('any');
    navigationConfig = [
      {
        id: 'applications',
        title: 'APPLICATIONS',
        translate: 'APPLICATIONS',
        type: 'group',
        icon: 'apps',
        children: [
          {
            id: 'dasboard',
            title: 'DASHBOARD',
            // translate: 'Dasboard',
            type: 'item',
            icon: 'home',
            url: 'apps/dashboard/dashboardPages',
          },
          {
            id: 'spesification',
            title: 'SPECIFICATION',
            type: 'item',
            icon: 'forward_rounded',
            url: 'apps/spesification',
          },
          {
            id: 'staggingRegistry',
            title: 'STAGING REGISTRATION',
            type: 'item',
            icon: 'post_add',
            url: 'apps/porcaheOrder',
          },
          {
            id: 'preStaging',
            title: 'PRE STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'checklistStaging',
                title: 'Pre Staging Checklist',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/checklistStagging/',
              },
            ],
          },
          {
            id: 'staging',
            title: 'STAGING',
            type: 'collapse',
            icon: 'check_box',
            children: [
              {
                id: 'stagingOldmachine',
                title: 'Staging Old Machine',
                type: 'item',
                disabled: true,
                icon: 'clear_all',
                url: 'apps/viewOldMachine',
                // url: 'apps/stagging/oldMachine',
              },
              {
                id: 'staggingNewMachine',
                title: 'Staging New Machine',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/viewNewMachine/',
                // url: 'apps/stagging/newMachine/',
              },
              {
                id: 'inspeksiTesting',
                title: 'Pre Loading Inspection',
                type: 'item',
                icon: 'verified_user',
                url: 'apps/stagging/inspeksiTestings/',
              },
            ],
          },
          {
            id: 'statusDelivery',
            title: 'STATUS DELIVERY',
            type: 'item',
            icon: 'local_shipping',
            url: 'apps/statusDelivery',
          },
          {
            id: 'warehouseTransfer',
            title: 'WAREHOUSE TRANSFER',
            type: 'item',
            icon: 'forward_rounded',
            url: 'apps/warehouseTransfer',
          },
          {
            id: 'summaryReport',
            title: 'SUMMARY',
            type: 'collapse',
            icon: 'library_books',
            children: [
              {
                id: 'summaryMachine',
                title: 'Summary Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/machine',
              },
              {
                id: 'summaryAccessories',
                title: 'Summary Accessories',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/accessories',
              },
              {
                id: 'summaryNewMachine',
                title: 'Summary New Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/Summary/newMachine',
              },
              {
                id: 'summaryOldMachine',
                title: 'Summary Old Machine',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/oldMachine',
              },
              {
                id: 'summaryDeliveryStatus',
                title: 'Summary Warehouse Transper',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouseTransper',
              },
              {
                id: 'summarywarehouse',
                title: 'Summary Warehouse',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/warehouse',
              },
              {
                id: 'summarypreStaging',
                title: 'Summary Pre Staging',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/preStaging',
              },
              {
                id: 'durationStagingSummary',
                title: 'Duration Staging Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationStagingSummary',
              },
              {
                id: 'durationReportSummary',
                title: 'Duration Report Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/durationReportSummary',
              },
              {
                id: 'developmentSummary',
                title: 'Development Summary',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/developmentSummary',
              },
              {
                id: 'warehouse',
                title: 'Summary Status Delivery',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/statusDelivery',
              },
              {
                id: 'summaryUps',
                title: 'Summary UPS',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/ups',
              },
              {
                id: 'deliveryRequest',
                title: 'Delivery Request',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/deliveryRequest',
              },
              {
                id: 'implementationTable',
                title: 'Implementation Table',
                type: 'item',
                icon: 'sticky_note_2',
                url: 'apps/summary/implementationTable',
              },
            ],
          },
          {
            id: 'mydatindo',
            title: 'MY DATINDO INTEGRATION',
            type: 'item',
            icon: 'launch',
            url: 'apps/myDatindoIntergration',
          },
        ],
      },
    ];
  } else {
    navigationConfig = [];
  }
}

export default navigationConfig;
