const MockDataMv400 = [
  { id: 1, item_desc: 'OS', valueDesc: 'OS' },
  { id: 2, item_desc: 'PROCESSOR', valueDesc: 'Processor' },
  { id: 3, item_desc: 'MAINBOARD_CE', valueDesc: 'Mainboard CE' },
  { id: 4, item_desc: 'MEMORY', valueDesc: 'Memory' },
  { id: 5, item_desc: 'MONITOR', valueDesc: 'Monitor' },
  { id: 6, item_desc: 'HDD', valueDesc: 'HDD' },
  { id: 7, item_desc: 'MCU', valueDesc: 'MCU' },
  { id: 8, item_desc: 'SPR', valueDesc: 'SPR' },
  { id: 9, item_desc: 'EPP', valueDesc: 'EPP' },
  { id: 10, item_desc: 'POWER_SUPPLY', valueDesc: 'Power Supply' },
  { id: 11, item_desc: 'CROPF', valueDesc: 'CROPF' },
  { id: 12, item_desc: 'BATRE_BACKUP', valueDesc: 'Batre Backup' },
  { id: 13, item_desc: 'CARDBIN', valueDesc: 'Cardbin' },
  { id: 14, item_desc: 'ID_SCANNER', valueDesc: 'Id Scanner' },
  { id: 15, item_desc: 'BILL_ACEPTOR', valueDesc: 'Bill Aceptor' },
  { id: 16, item_desc: 'PRINTER_A4', valueDesc: 'Printer A4' },
  { id: 17, item_desc: 'KUNCI FASCIA', valueDesc: 'Kunci Fascia' },
  { id: 18, item_desc: 'KUNCI_BILL_ACEPTOR', valueDesc: 'Kunci Bill Aceptor' },
  { id: 19, item_desc: 'KUNCI CARDBIN', valueDesc: 'Kunci Cardbin' },
  { id: 20, item_desc: 'SAFE DOOR KEY', valueDesc: 'Safe Door Key' },
  { id: 21, item_desc: 'CONTACTLESS', valueDesc: 'Contactless' },
  { id: 22, item_desc: 'LAN CARD', valueDesc: 'LAN Card' },
  { id: 23, item_desc: 'THERMAL PAPER', valueDesc: 'Thermal Paper' },
  { id: 24, item_desc: 'A4_PAPER', valueDesc: 'A4 Paper' },
  { id: 25, item_desc: 'ROLL_PEREKAT', valueDesc: 'Roll Perekat' },
  { id: 26, item_desc: 'RIBBON', valueDesc: 'Ribbon' },
  { id: 27, item_desc: 'CABINET SENSOR', valueDesc: 'Cabinet Sensor' },
  { id: 28, item_desc: 'KABEL LAN', valueDesc: 'Kabel LAN' },
  { id: 29, item_desc: 'KABEL POWER', valueDesc: 'Kabel Power' },
  { id: 30, item_desc: 'KABEL SERIAL UPS', valueDesc: 'Kabel Serial UPS' },
  { id: 31, item_desc: 'KVA', valueDesc: 'KVA' },
  { id: 32, item_desc: 'FDI', valueDesc: 'FDI' },
  { id: 33, item_desc: 'PIN COVER', valueDesc: 'PIN Cover' },
];
export default MockDataMv400;
