const MockDataCRM = [
  { id: 1, item_desc: 'OS', valueDesc: 'OS' },
  { id: 2, item_desc: 'PROCESSOR', valueDesc: 'Processor' },
  { id: 3, item_desc: 'MAINBOARD_CE', valueDesc: 'Mainboard CE' },
  { id: 4, item_desc: 'MEMORY', valueDesc: 'Memory' },
  { id: 5, item_desc: 'MONITOR', valueDesc: 'Monitor' },
  { id: 6, item_desc: 'HDD', valueDesc: 'HDD' },
  { id: 7, item_desc: 'MCU', valueDesc: 'MCU' },
  { id: 8, item_desc: 'SPR', valueDesc: 'SPR' },
  { id: 9, item_desc: 'EPP', valueDesc: 'EPP' },
  { id: 10, item_desc: 'POWER_SUPPLY', valueDesc: 'Power Supply' },
  { id: 11, item_desc: 'CROPF', valueDesc: 'CROPF' },
  { id: 12, item_desc: 'CARDBIN', valueDesc: 'Cardbin' },
  { id: 13, item_desc: 'CASSETTE', valueDesc: 'Cassette' },
  { id: 14, item_desc: 'REJECT', valueDesc: 'Reject' },
  { id: 15, item_desc: 'UTC', valueDesc: 'UTC' },
  { id: 16, item_desc: 'KUNCI FASCIA ATAS', valueDesc: 'Kunci Fascia Atas' },
  { id: 17, item_desc: 'KUNCI FASCIABAWAH', valueDesc: 'Kunci Fascia Bawah' },
  { id: 18, item_desc: 'KUNCI_TENGAH', valueDesc: 'Kunci Tengah' },
  { id: 19, item_desc: 'KUNCI_TOMBAK', valueDesc: 'Kunci Tombak' },
  { id: 20, item_desc: 'KUNCI CASSETTE/REJECT', valueDesc: 'Kunci Cassette/Reject' },
  { id: 21, item_desc: 'KUNCI CARDBIN', valueDesc: 'Kunci Cardbin' },
  { id: 22, item_desc: 'SAFE DOOR', valueDesc: 'Safe Door' },
  { id: 23, item_desc: '3 WAY LOCK', valueDesc: '3 way Lock' },
  { id: 24, item_desc: 'AS CENCON', valueDesc: 'As Cencon' },
  { id: 25, item_desc: 'BRACKET CAMERA', valueDesc: 'BRACKET CAMERA' },
  { id: 26, item_desc: 'CONTACTLESS', valueDesc: 'Contactless' },
  { id: 27, item_desc: 'PROXIMITY SENSOR', valueDesc: 'PROXIMITY SENSOR' },
  { id: 28, item_desc: 'LAN CARD', valueDesc: 'LAN Card' },
  { id: 29, item_desc: 'THERMAL PAPER', valueDesc: 'Thermal Paper' },
  { id: 30, item_desc: 'CABINET SENSOR', valueDesc: 'Cabinet Sensor' },
  { id: 31, item_desc: 'SENSOR GETAR', valueDesc: 'Sensor Getar' },
  { id: 32, item_desc: 'KABEL LAN', valueDesc: 'Kabel LAN' },
  { id: 33, item_desc: 'KABEL POWER', valueDesc: 'Kabel Power' },
  { id: 34, item_desc: 'KABEL SERIAL_UPS', valueDesc: 'Kabel Serial UPS' },
  { id: 35, item_desc: 'KVA', valueDesc: 'KVA' },
  { id: 36, item_desc: 'KABEL HDMI TO DVI', valueDesc: 'Kabel HDMI to DVI' },
  { id: 37, item_desc: 'FDI', valueDesc: 'FDI' },
  { id: 38, item_desc: 'PIN COVER', valueDesc: 'PIN Cover' },
  { id: 39, item_desc: 'PELINDUNG CASSETTE', valueDesc: 'PELINDUNG CASSETTE' },
];
export default MockDataCRM;
